/**
 * Copyright 2008 EscapeK
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *     
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 * 
 * --------------------------------------------------------------------------
 * $Id$
 * --------------------------------------------------------------------------
 */
package org.escapek.mofparser.decl;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Stores data read from a qualifier use.
 * @author nico
 *
 */
public class Qualifier {
	/**
	 * Name of the Qualifier used for this qualifier
	 */
	public String name;
	
	/**
	 * Type of the Qualifier type used for this qualifier.
	 * May be null when generated by parser, as it can't guess the data type
	 * of a qualifier parsed.
	 */
	public TypeDecl type;

	/**
	 * Value given to the qualifier
	 */
	public List<String> value;
	
	/**
	 * List of flavors given to the qualifier
	 */
	public Set<String> flavors;
	
	public Qualifier() {
		flavors = new HashSet<String>();
		value = new ArrayList<String>();
	}

	public Qualifier(String qualifierName) {
		this();
		this.name = qualifierName;
	}

	@Override
	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if((obj == null) || (obj.getClass() != this.getClass()))
			return false;
			
		return name.equalsIgnoreCase(((Qualifier) obj).name);
	}

	@Override
	public int hashCode() {
		if(name != null) {
			return name.hashCode();
		}
		return super.hashCode();
	}
}
